const SCREENPLAY_SKIP = new Set(
  [
    "int",
    "ext",
    "i/e",
    "int/ext",
    "day",
    "night",
    "morning",
    "evening",
    "afternoon",
    "dusk",
    "dawn",
    "later",
    "continuous",
    "same",
    "moment",
    "flashback",
    "montage",
    "intercut",
    "cut",
    "to",
    "fade",
    "in",
    "out",
    "dissolve",
    "smash",
    "wipe",
    "super",
    "title",
    "close",
    "closeup",
    "cu",
    "ecu",
    "wide",
    "ws",
    "mws",
    "angle",
    "pov",
    "insert",
    "os",
    "o.s.",
    "vo",
    "v.o.",
    "cont'd",
    "contd",
    "continued",
    "more",
    "adlib",
    "beat",
    "pause",
    "then",
    "off",
    "screen",
    "prelap",
    "match",
  ].map((w) => w.replace(/\./g, ""))
);

const COMMON_ENGLISH = new Set(
  [
    "the",
    "a",
    "an",
    "and",
    "or",
    "but",
    "if",
    "of",
    "on",
    "at",
    "to",
    "for",
    "from",
    "with",
    "without",
    "into",
    "onto",
    "over",
    "under",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "am",
    "i",
    "you",
    "he",
    "she",
    "it",
    "we",
    "they",
    "me",
    "him",
    "her",
    "us",
    "them",
    "my",
    "your",
    "his",
    "their",
    "this",
    "that",
    "these",
    "those",
    "not",
    "no",
    "yes",
    "do",
    "does",
    "did",
    "don't",
    "dont",
    "can't",
    "cant",
    "won't",
    "wont",
    "have",
    "has",
    "had",
    "will",
    "would",
    "could",
    "should",
    "can",
    "may",
    "might",
    "must",
    "what",
    "when",
    "where",
    "who",
    "why",
    "how",
    "which",
    "there",
    "here",
    "then",
    "than",
    "so",
    "just",
    "about",
    "up",
    "down",
    "out",
    "off",
    "again",
    "once",
    "only",
    "also",
    "very",
    "too",
    "as",
    "by",
    "hello",
    "please",
    "sorry",
    "thanks",
    "okay",
    "ok",
    "phone",
    "window",
    "table",
    "rain",
    "hits",
    "vibrates",
    "told",
    "call",
    "again",
    "quietly",
    "living",
    "room",
  ].map((w) => w.toLowerCase())
);

export function normalizeSkipKey(word: string): string {
  return word.toLowerCase().replace(/[.’']/g, "").replace(/\./g, "");
}

export function isScreenplayJargon(word: string): boolean {
  return SCREENPLAY_SKIP.has(normalizeSkipKey(word));
}

export function isLikelyEnglish(word: string): boolean {
  const key = normalizeSkipKey(word);
  if (COMMON_ENGLISH.has(key)) return true;
  if (/^[A-Z]{2,}$/.test(word) && word.length <= 4) return true;
  return false;
}

export function shouldKeepLatin(word: string, mixed: boolean): boolean {
  if (!/^[A-Za-z][A-Za-z''.-]*$/.test(word)) return true;
  if (isScreenplayJargon(word)) return true;
  if (/^[A-Z]{2,}$/.test(word)) return true;
  if (mixed && isLikelyEnglish(word)) return true;
  return false;
}
